FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["TestTaskQuestions.csproj", "./"]
RUN dotnet restore "TestTaskQuestions.csproj"

COPY . .
RUN dotnet publish "TestTaskQuestions.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "TestTaskQuestions.dll"]